"""Build AgentStream.app — a macOS menu bar companion.

Usage:
    python setup_mac.py py2app          # build the .app bundle
    python setup_mac.py py2app -A       # alias build (dev, faster)

The resulting app appears in dist/AgentStream.app.
"""

import os
import sys

from setuptools import setup

# Determine the version dynamically
version = "1.0.0"
init_path = os.path.join("agentstream", "__init__.py")
if os.path.exists(init_path):
    with open(init_path) as f:
        for line in f:
            if line.startswith("__version__"):
                version = line.split("=")[1].strip().strip("\"'")
                break

# Icon path (generated by macos/create_icon.py)
icon_path = os.path.join("assets", "AgentStream.icns")
icon_file = icon_path if os.path.exists(icon_path) else None

APP = ["macos/AgentStream.py"]
DATA_FILES = []
OPTIONS = {
    "argv_emulation": False,
    "iconfile": icon_file,
    "plist": {
        "CFBundleName": "AgentStream",
        "CFBundleDisplayName": "AgentStream",
        "CFBundleIdentifier": "com.agentstream.toolbar",
        "CFBundleVersion": version,
        "CFBundleShortVersionString": version,
        # LSUIElement=True → menu-bar-only app (no Dock icon)
        "LSUIElement": True,
        "LSMinimumSystemVersion": "10.15",
        "NSHumanReadableCopyright": "MIT License",
        "NSHighResolutionCapable": True,
    },
    "packages": ["agentstream"],
    "includes": ["rumps"],
    # Exclude heavy packages that aren't needed in the .app
    "excludes": [
        "tkinter",
        "unittest",
        "pydoc",
        "doctest",
        "test",
        "distutils",
        "setuptools",
        "pip",
    ],
}

setup(
    name="AgentStream",
    version=version,
    app=APP,
    data_files=DATA_FILES,
    options={"py2app": OPTIONS},
    setup_requires=["py2app"],
)
